name: Deploy to GitHub Pages

on:
  push:
    branches: ['production']

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    
      - name: Checkout
        uses: actions/checkout@v6
        
      - name: Setup Node.js
        uses: actions/setup-node@v6
        with:
          node-version: '24.x'
          
      - name: Install
        run: npm install
        
      - name: Build
        run: npm run build
        
      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: dist/soltech-site/browser  # Double check your exact local output path
          branch: gh-pages
